### ISSUE TITLE
bug aac 6s

### ISSUE THREAD

**Issue by linKnowEasy** [whiteblue3/HTTPLiveStreaming#1]
貌似在6s 手机采集不到音频数据

**Comment by whiteblue3** [comment]
Thank you bug report. I'll check this.

**Comment by linKnowEasy** [comment]
maybe because 6s caback data audio pcm( (CMSampleBufferRef)sampleBuffer ) buffer length is 940/941 not be 1024

**Comment by boyXiong** [comment]
不是问题 解决了没，我在测试 6 的真机上面 也没有ACC 数据

**Comment by boyXiong** [comment]
不知道 问题 解决了，我在 6 上面，也采样不到 AAC 数据

**Comment by feng520ckx** [comment]
采样率的原因 设置成48K 应该可以
